In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import seaborn as sn
import matplotlib.pyplot as plt
import numpy as np

In [2]:
import pandas as pd
candidates = {'gmat': [780,750,690,710,680,730,690,720,740,690,610,690,710,680,770,610,580,650,540,590,620,600,550,550,570,670,660,580,650,660,640,620,660,660,680,650,670,580,590,690],
              'gpa': [4,3.9,3.3,3.7,3.9,3.7,2.3,3.3,3.3,1.7,2.7,3.7,3.7,3.3,3.3,3,2.7,3.7,2.7,2.3,3.3,2,2.3,2.7,3,3.3,3.7,2.3,3.7,3.3,3,2.7,4,3.3,3.3,2.3,2.7,3.3,1.7,3.7],
              'work_experience': [3,4,3,5,4,6,1,4,5,1,3,5,6,4,3,1,4,6,2,3,2,1,4,1,2,6,4,2,6,5,1,2,4,6,5,1,2,1,4,5],
              'admitted': [1,1,0,1,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,0,1,0,0,0,0,1,1,0,1,1,0,0,1,1,1,0,0,0,0,1]
              }

df = pd.DataFrame(candidates,columns= ['gmat', 'gpa','work_experience','admitted'])
print (df)

    gmat  gpa  work_experience  admitted
0    780  4.0                3         1
1    750  3.9                4         1
2    690  3.3                3         0
3    710  3.7                5         1
4    680  3.9                4         0
5    730  3.7                6         1
6    690  2.3                1         0
7    720  3.3                4         1
8    740  3.3                5         1
9    690  1.7                1         0
10   610  2.7                3         0
11   690  3.7                5         1
12   710  3.7                6         1
13   680  3.3                4         0
14   770  3.3                3         1
15   610  3.0                1         0
16   580  2.7                4         0
17   650  3.7                6         1
18   540  2.7                2         0
19   590  2.3                3         0
20   620  3.3                2         1
21   600  2.0                1         0
22   550  2.3                4         0
23   550  2.7   

In [309]:
X = df[['gmat', 'gpa','work_experience']]
y = df['admitted']

In [310]:
X = np.array(X)

In [19]:
theta_0 = X[:, 0]

In [21]:
theta_0 = 0

In [205]:
theta_1 = 0
theta_2 = 0
theta = np.array([0, 0, 0])
predict = np.dot(np.transpose(theta), np.transpose(X))

In [95]:
z = np.zeros(40)
for i in range(40):
    z[i] = math.exp(-1*predict[i])

In [96]:
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [97]:
z = np.array(z)


In [116]:
h_x = 1/(1 + np.exp(np.dot(np.transpose(theta), np.transpose(X))))
h_x

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5])

In [363]:
L = 0.0001
theta_0 = 0
theta_1 = 0

theta_2 = 0


theta = np.array([0, 0, 0])
for i in range(10000):
    z = np.dot(np.transpose(theta), np.transpose(X))
    h_x = 1/(1 + np.exp(-z))
    der0 = (1/40) * sum(X[:, 0]*(h_x - y))
    der1 = (1/40) * sum(X[:, 1]*(h_x - y))
    der2 = (1/40) * sum(X[:, 2]*(h_x - y))
    theta_1 = theta_1 - L*der1
    theta_0 = theta_0 - L*der0
    theta_2 = theta_2 - L*der2
    theta = [theta_0, theta_1, theta_2]
    
    

In [364]:
h_x

array([0.51864129, 0.5212365 , 0.50403181, 0.52198316, 0.51543819,
       0.5297307 , 0.48160259, 0.51262715, 0.520387  , 0.47548287,
       0.49126606, 0.52032722, 0.52807733, 0.50931094, 0.51066592,
       0.48211921, 0.49488655, 0.52311369, 0.47936115, 0.48552291,
       0.4921168 , 0.4710959 , 0.48831274, 0.47409253, 0.48490791,
       0.52068987, 0.51173834, 0.47859294, 0.52311369, 0.51375919,
       0.48460481, 0.48598873, 0.51480172, 0.51986178, 0.51541669,
       0.47829012, 0.49013361, 0.48269568, 0.48550141, 0.52032722])

In [283]:
y

0     1
1     1
2     0
3     1
4     0
5     1
6     0
7     1
8     1
9     0
10    0
11    1
12    1
13    0
14    1
15    0
16    0
17    1
18    0
19    0
20    1
21    0
22    0
23    0
24    0
25    1
26    1
27    0
28    1
29    1
30    0
31    0
32    1
33    1
34    1
35    0
36    0
37    0
38    0
39    1
Name: admitted, dtype: int64

In [365]:
check = np.zeros(40)
for i in range(40):
    if(h_x[i]) > 0.5:
        check[i] = 1
    else:
        check[i] = 0
        

In [366]:
check

array([1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       1., 0., 0., 0., 0., 1.])

In [367]:
counter = 0
for i in range(40):
    if(y[i] == check[i]):
        counter = counter+1
        
accurate = counter/40
accurate

0.9

In [328]:
X[:,0] = (X[:,0]-660)/240

In [329]:
X

array([[ 0.5       ,  0.5       , -0.1       ],
       [ 0.375     ,  0.45652174,  0.1       ],
       [ 0.125     ,  0.19565217, -0.1       ],
       [ 0.20833333,  0.36956522,  0.3       ],
       [ 0.08333333,  0.45652174,  0.1       ],
       [ 0.29166667,  0.36956522,  0.5       ],
       [ 0.125     , -0.23913043, -0.5       ],
       [ 0.25      ,  0.19565217,  0.1       ],
       [ 0.33333333,  0.19565217,  0.3       ],
       [ 0.125     , -0.5       , -0.5       ],
       [-0.20833333, -0.06521739, -0.1       ],
       [ 0.125     ,  0.36956522,  0.3       ],
       [ 0.20833333,  0.36956522,  0.5       ],
       [ 0.08333333,  0.19565217,  0.1       ],
       [ 0.45833333,  0.19565217, -0.1       ],
       [-0.20833333,  0.06521739, -0.5       ],
       [-0.33333333, -0.06521739,  0.1       ],
       [-0.04166667,  0.36956522,  0.5       ],
       [-0.5       , -0.06521739, -0.3       ],
       [-0.29166667, -0.23913043, -0.1       ],
       [-0.16666667,  0.19565217, -0.3  